# Generated by Django 6.0.4 on 2026-04-13 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_artigo_categoria_artigo_data_publicacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='artigos/'),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='categoria',
            field=models.CharField(choices=[('rhea', 'Rhea Ripley'), ('pinky', 'Pinkchyuwu'), ('natty', '6nattynat')], default='rhea', max_length=20),
        ),
    ]
